build:
  maxIssues: 0
  excludeCorrectable: true

config:
  validation: true

naming:
  FunctionNaming:
    ignoreAnnotated:
      - Composable
      - Preview

complexity:
  LongMethod:
    active: true
    threshold: 60