build:
  maxIssues: 0
  excludeCorrectable: true

config:
  validation: true

naming:
  FunctionNaming:
    ignoreAnnotated:
      - Composable
      - Preview

style:
  MagicNumber:
    ignorePropertyDeclaration: true
  UnusedPrivateMember:
    ignoreAnnotated:
      - Preview
  MaxLineLength:
    maxLineLength: 140
  ReturnCount:
    max: 4

complexity:
  LongMethod:
    active: true
    threshold: 120
  LongParameterList:
    active: true
    functionThreshold: 10
  CyclomaticComplexMethod:
    active: true
    threshold: 30
  TooManyFunctions:
    active: true
    thresholdInClasses: 30
    thresholdInInterfaces: 30
    thresholdInObjects: 30
    thresholdInFiles: 30

Compose:
  ComposableAnnotationNaming:
    active: true
  ComposableNaming:
    active: true
  ComposableParamOrder:
    active: true
  CompositionLocalAllowlist:
    active: true
  CompositionLocalNaming:
    active: true
  ContentEmitterReturningValues:
    active: true
  ContentTrailingLambda:
    active: true
  ContentSlotReused:
    active: true
  DefaultsVisibility:
    active: true
  LambdaParameterEventTrailing:
    active: true
  LambdaParameterInRestartableEffect:
    active: true
  ModifierClickableOrder:
    active: true
  ModifierComposed:
    active: true
  ModifierMissing:
    active: true
  ModifierNaming:
    active: true
  ModifierNotUsedAtRoot:
    active: true
  ModifierReused:
    active: true
  ModifierWithoutDefault:
    active: true
  MultipleEmitters:
    active: true
  MutableParams:
    active: true
  MutableStateAutoboxing:
    active: true
  MutableStateParam:
    active: true
  ParameterNaming:
    active: true
  PreviewAnnotationNaming:
    active: true
  PreviewPublic:
    active: true
  RememberMissing:
    active: true
  RememberContentMissing:
    active: true
  ViewModelForwarding:
    active: true
  ViewModelInjection:
    active: true
